### ISSUE TITLE
Error on "Error index out of bounds"

### ISSUE THREAD

**Issue by buddha314** [ct-clmsn/chapel-module-matrixmarket#5]
The [MM format](http://math.nist.gov/MatrixMarket/formats.html) states that the header has three values like `5 5 6`  which indicate the number rows, columns and entries respectively.

The head of my file

```
%%MatrixMarket matrix coordinate real general
60563 569425 314056
1 99609 1.0
1 122912 1.0
1 138968 1.0
2 7870 1.0
2 7871 1.0
2 7876 1.0
2 51987 1.0
2 219571 1.0
```

Indicating 60,563 rows, 569,425 columns and 314056 entries.  However, when running this I get

```
$CHPL_HOME/modules/internal/ChapelDistribution.chpl:583: error: halt reached - Sparse domain/array index out of bounds: (60589, 25906) (expected to be within {1..60563, 1..569425})
make: *** [core] Error 1
```

If you get for that line, however, you see the `(i,j)` entries are reversed

```
> cat data/condition_cui.txt | grep 60589
25906 60589 1.0
```

So this should be within bounds.

**Comment by buddha314** [comment]
Gee, I wish we could get that handsome @bradcray to stop by...

**Comment by buddha314** [comment]
And it's almost certainly worth pointing out that I was NOT receiving this error before I made this switch to lines 367-369

```
     Dtoret = {1..nrows, 1..ncols};
     //var spDom : sparse subdomain(Dtoret);
     var spDom : sparse subdomain(Dtoret) dmapped CS();
```

Just confirmed, going back to original w/o `dmapped CS()` and there is no problem

**Comment by bradcray** [comment]
Does this mean that you got past the compilation problem you mentioned [here](https://github.com/ct-clmsn/MatrixMarket/issues/4#issuecomment-331551358)?

**Comment by buddha314** [comment]
Not sure, I turned off `--fast` to get it to run.  Running without that now and with the `dmapped CS()` and (bonus!) with `--devel` but it takes a few

**Comment by bradcray** [comment]
Probably the reason you started getting the error had less to do with switching to dmapped CS() and more to compiling without --fast.  When --fast is on, we don't waste any time doing bounds checking, so you wouldn't have gotten the out-of-bounds error above.  Out of curiosity, are the lines surrounding the "bad index" line well-formed?

**Comment by buddha314** [comment]
This is looking like an issue with the `.T` function in the `LinearAlgebra` package that @ben-albrecht put together.  There were too many switches happening!

**Comment by bradcray** [comment]
I think you're right—I don't think this has anything to do with MatrixMarket, and that @ben-albrecht's transpose routine is assuming square sparse matrices and/or isn't transposing the matrix shape such that it thinks the transposed coordinates are OOB.  I suggest closing this issue and taking the issue back to Chapel-land.

**Comment by buddha314** [comment]
Right-oh!  To be fair, I may have provided bad specs to Ben and said something like "let's do symmetric for now".  Closing.

**Comment by ct-clmsn** [comment]
@bradcray, @buddha314 Glad to see people using MatrixMarket but, man, ya'll are stressing me out. :P

**Comment by buddha314** [comment]
Consider a compliment!  As I just mentioned to Ben, it's either this or writing code nobody uses.
